Repository cockroachdb/replicator, pull requests merged in 2024-06, with the labels that each got.

#900 ndjson: moving ndjson parser to the util package so they can be reused.
  internal/source/cdc/handler.go
  internal/source/cdc/handler_test.go
  internal/source/cdc/ndjson.go
  internal/source/cdc/primary_key.go
  internal/source/cdc/provider.go
  internal/source/cdc/request.go
  internal/source/cdc/url_test.go
  internal/source/cdc/webhook_query.go
  internal/util/cdcjson/ndjson_parser.go
  internal/util/cdcjson/ndjson_parser_test.go
  internal/util/cdcjson/query_payload.go
  internal/util/cdcjson/query_payload_test.go
  internal/util/cdcjson/reader.go
  internal/util/cdcjson/reader_test.go
Labels: R-exclude

#901 seqtest: Make CheckSequencer work with Immediate
  internal/cmd/workload/workload_test.go
  internal/sequencer/besteffort/besteffort_test.go
  internal/sequencer/core/core_test.go
  internal/sequencer/immediate/immediate_test.go
  internal/sequencer/seqtest/check.go
  internal/sequencer/switcher/switcher_test.go
  internal/sinktest/all/workload.go
  internal/source/cdc/handler_test.go
Labels: R-exclude

#903 objstore: adding ErrTransient and ErrSkipAll error markers.
  internal/source/objstore/bucket/errors.go
  internal/source/objstore/providers/local/local.go
  internal/source/objstore/providers/local/local_test.go
  internal/source/objstore/providers/s3/s3.go
  internal/source/objstore/providers/s3/s3_test.go
  internal/source/objstore/providers/storetest/suite.go
Labels: R-exclude

#907 core: Apply and Mark concurrently
  internal/sequencer/core/round.go
Labels: R-exclude

#913 memo: adding in-memory implementation.
  internal/staging/memo/memory.go
  internal/staging/memo/memory_test.go
Labels: R-exclude

#916 sinkprod: Reenable version ratchet
  internal/sinkprod/target.go
  internal/source/cdc/server/wire_gen.go
  internal/source/kafka/wire_gen.go
  internal/source/mylogical/wire_gen.go
  internal/source/pglogical/wire_gen.go
Labels: R-bugfix

#918 go.mod: Update go to 1.22.4
  go.mod
Labels: R-bugfix

#905 objstore: initial implementation
  go.mod
  go.sum
  internal/cmd/objstore/objstore.go
  internal/cmd/objstore/objstore_test.go
  internal/sinktest/mocks/bucket.go
  internal/sinktest/mocks/collector.go
  internal/sinktest/mocks/docs.go
  internal/sinktest/mocks/processor.go
  internal/source/objstore/bucket/bucket.go
  internal/source/objstore/config.go
  internal/source/objstore/conn.go
  internal/source/objstore/conn_test.go
  internal/source/objstore/conveyor.go
  internal/source/objstore/eventproc/local.go
  internal/source/objstore/injector.go
  internal/source/objstore/metrics.go
  internal/source/objstore/objstore.go
  internal/source/objstore/provider.go
  internal/source/objstore/provider_string.go
  internal/source/objstore/state.go
  internal/source/objstore/wire_gen.go
  main.go
Labels: enhancement, R-enhancement

#925 script: Allow custom routing of deletions
  internal/script/loader.go
  internal/script/script.go
  internal/script/script_test.go
  internal/script/testdata/main.ts
  internal/script/testdata/replicator@v1.d.ts
  internal/sequencer/script/acceptor.go
  internal/sequencer/script/script_test.go
  internal/sinktest/scripttest/testdata/logical_test.ts
Labels: R-enhancement
